trigger:
  branches: 
    include: 
    - main
  paths:
    exclude:
    - /Maestro/subscriptions.json
    - /build-info/docker/*.json

pr:
  branches: 
    include: 
    - main
  paths:
    exclude:
    - /Maestro/subscriptions.json
    - /build-info/docker/*.json

jobs:
- job: innerloop
  displayName: Windows build
  pool:
    vmImage: windows-2019
  steps:
  - checkout: self
    clean: true
  - script: .\Maestro\build.cmd
