trigger:
- main
  paths:
    exclude:
    - subscriptions.json
    - /build-info/docker/*.json

pr:
- main
  paths:
    exclude:
    - subscriptions.json
    - /build-info/docker/*.json

jobs:
- job: innerloop
  displayName: Windows build
  pool:
    vmImage: windows-2019
  steps:
  - checkout: self
    clean: true
  - script: .\Maestro\build.cmd
